---
title: ""
params:
  day: 3
  ptitle: true
  pbackground: true
  dtype: "none"
---

# Welcome to class! {data-background=#e8c35d}

The Data Science Process: Day 1

## Today's Outline:

>- Case Study 1
>- Team Leads
>- Saving and sharing your work
>- R Programming
>- Exploratory Data Analysis

## Case Study 1

## Other questions?

# Saving and Sharing Your Work {data-background=#e8c35d}

## Motivating Problem

## R vs R Scripts

## Markdown

## R Markdown

[What is R Markdown?](https://rmarkdown.rstudio.com/lesson-1.html)

## Possibilities with R Markdown

- Microsoft Word document
- Slide show
- Html slides
- Website
- Blog
- PDF report
- Dashboard

## When to use what

# R Programming {data-background=#e8c35d}

##

not sure if this section is necessary? You're definitely gonna run out of time...

## [Data Types](https://www.geeksforgeeks.org/r-data-types/)

- Each variable in R has an associated data type
- Each data type requires different amounts of memory
- Each data type has some specific operations which can be performed over it
  - **Numeric:** Set of all real numbers
  - **Integer:** Set of all integers
  - **Logical:** TRUE and FALSE
  - **Complex:** Set of complex numbers
  - **Character:** "a", "BYU-Idaho", "lions and tigers and bears", "@", "3"

## [Vectors](http://adv-r.had.co.nz/Data-structures.html)

- The basic data structure in R is the vector
- Vectors come in two flavors: atomic vectors and lists
- Atomic vectors and lists have three common properties:
  - **Type:** typeof(), what it is.
  - **Length:** length(), how many elements it contains.
  - **Attributes:** attributes(), additional arbitrary metadata.
- They differ in the types of their elements: 
  - All elements of an atomic vector must be the same type
  - The elements of a list can have different types.

## Dataframes

# Exploratory Data Analysis {data-background=#e8c35d}

## What is EDA?

## Goal of EDA

Like one of those awkward ice breakers on the first day of school, you're trying to learn enough about the data that you can introduce it to other people. Try asking:

- What are the data types? (Numeric, character, etc.)
- What is the distribution of each variable?
- Are there any extreme values?
- Is there missing data? Where? Why?
- Are there any obvious relationships between variables?

## Where does EDA fit in the data science process?

A client sets up a meeting with you to discuss an upcoming project. She also sends you multiple csv files with data she has collected. Before the meeting, you use EDA to answer some important questions:

- *What type of information is stored in this data?*
- *What can I do with this data?*
- *What can I not do with this data?*
- *Does anything look suspicious?*

## Where does EDA fit in the data science process?

You've been asked to...

- *Do I have all the information I need?*
- *What is the best way to combine data sets?*
- *What wrangling is needed to get the data in the right format?*

## Example Data

*have the students generate questions about a data set*

## EDA in R

*and then try to answer those questions in R*

