---
title: ""
params:
  ptitle: true
  pbackground: true
  dtype: "none"
---

# Welcome to class! {data-background=#e8c35d}

Tidy Data: Day 1

# Case Study Presentations {data-background=#e8c35d}

# Tidy Data  {data-background=#e8c35d}

## What is tidy data?

<br>

> - [Tidy data paper](https://r4ds.had.co.nz/tidy-data.html)
> - [Tidy data chapter](https://r4ds.had.co.nz/tidy-data.html)
> - [Slides by Julie Lowndes and Allison Horst](https://www.openscapes.org/blog/2020/10/12/tidy-data/)
> - [Example of untidy and "wild" data](https://sharlagelfand.netlify.app/posts/tidying-toronto-open-data/)

## `tidyr` Functions: Character vectors

<br>

- `separate()` separates a character column into multiple columns (using regular expression or numeric locations)
- `extract()` extracts text from a character column into multiple columns (using regular expression groups)
- `unite()` unites multiple columns into one by pasting strings together


<!-----------
## regular expressions

A **regular expression** is a sequence of characters that define a search pattern.

Usually such patterns are used by string-searching algorithms for "find" or "find and replace" operations on strings, or for input validation.

[regex101.com](https://regex101.com/)
------------->

## `tidyr` Functions: Pivoting

<br>

- `pivot_longer()` pivots data from wide to long
- `pivot_wider()` pivots data from long to wide


## `tidyr` Functions: Pivoting

<br>

Start with `relig_income` and `pivot_longer` to create two new columns: income and count

```
library(tidyverse)
relig_income
```

## `tidyr` Functions: Pivoting

<br>

Start with `fish_encounters` and `pivot_wider` to create a new column for each station. Fill in missing values with 999.

```
library(tidyverse)
fish_encounters
```

## `tidyr` Functions: Pivoting

<br>

> - [Helpful illustration](https://bookdown.org/ansellbr/WEHI_tidyR_course_book/reading-tidying-joining-data.html#pivot_wider)
> - [More illustrations](https://swcarpentry.github.io/r-novice-gapminder/14-tidyr/)


## `dyplr` and `tidyr`

<br>

The six data verbs from `dyplr` and the tidy tools from `tidyr` should be used hand-in-hand to wrangle data until it is tidy.

[What it might feel like.](https://www.youtube.com/watch?v=ry55--J4_VQ)

## Task 7

<br>

Two problems you are going to run into:

>- Month names are not always spelled correctly 
>- Getting the months in the correct order for the table