---
title: ""
---

# Welcome to Class! {data-background=#e8c35d}

# Good Charts {data-background=#e8c35d}

## Chapter 4: Better charts in a couple of hours

<br>

Sister Allen's favorite quotes

- "Programs visualize data. People visualize ideas."
- The Talk and Listen step will "be the most revelatory, but also possibly the least natural."
- "Sketching is generative; it's meant to bring up ideas. Prototyping is iterative; it's meant to hone good ones."

# Making Charts in Tableau {data-background=#e8c35d}

## Workflow

<br>

For each case study, you should...

1. Start a new Tableau "workbook" by opening a dataset
2. Load any other data you need
3. Make charts. Lots of charts!
4. Save your Tableau workbook often
5. Export your final charts and create a presentation

## Case Study 2

<br>

What do you need to submit in I-Learn?

- Your data (.csv or .xlsx)
- Your 6-slide presentation
  - The presentation and charts must be your own!
  - Do not just paste your charts into the slides. You also have to write a description.

## Teach One Another Quiz

<br>

Due date moved to *Monday*.

1. Share a "tool tip" in Slack.
1. Present your case study to a classmate and get feedback (in class).
1. Provide feedback on another student's case study (in class).

## Let's practice!

<br>

Remind me to show you:

>- Histogram
>- Bar chart
>- Scatterplot
>- Boxplot