---
title: ""
---

# Welcome to class! {data-background=#e8c35d}
<!--- # From Data Decisions to Population Decisions ---->

## Case Study Presentations

<br>

In your groups:

- Go around in a circle and introduce yourselves. 
- Present your case study to your group members. (If you did not finish your case study, then tell your group members what your game plan is to finish it.)
- Provide your group members with feedback after they present.
- Remember to post a Tool Tip in Slack!


# Descriptive and Inferential Statistics {data-background=#e8c35d}


## Sampling from a Population

<br>

The goal of statistical analysis is to determine if what we see in a **sample** is likely to occur in the **population**. 

- For example, if we observe a common trend among 100 BYU-Idaho students can we assume that that trend will hold for all BYU-Idaho students? 
- Or as a made-up, larger scale example:
    - Assume that 1000 Toyota Camrys are tested and 1% of them are found to have a defect in the braking system. 
    - Can Toyota assume that 1% of all Toyota Camrys will have the same defect? 
- **Statistical analysis allows us to answer to these questions.**

## Descriptive vs. Inferential Statistics





# Hypothesis Testing {data-background=#e8c35d}


## Fisher's Tea Experiment

<br>

<iframe width="560" height="315" src="https://www.youtube.com/embed/lgs7d5saFFc" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

- Fisher wondered whether Bristol had simply gotten lucky and guessed correctly all eight times. He worked out the math for this possibility and realized the odds were 1 in 70. So she probably could taste the difference. [ref](https://www.sciencehistory.org/distillations/ronald-fisher-a-bad-cup-of-tea-and-the-birth-of-modern-statistics)

## Setting up the Tea experiment

<br>

> - What is the null hypothesis?
> - What is the alternative hypothesis?
> - What proof is needed to persuade us of one hypothesis or the other?

## Fisher's follow on questions

<br>

- What if she had switched two cups around, incorrectly identifying a tea-first cup as a milk-first cup and vice versa? Can she still tell the difference?
- Would 12 coups instead of eight cups have been a better test? Why?
- What if she was only given two cups and correctly identified both, could we conclude that she had the ability to taste the difference?

## What is a p-value?

## What is a p-value?

<br>

[In statistics, the p-value is the probability of obtaining results as extreme as the observed results of a statistical hypothesis test, *assuming that the null hypothesis is true.*](https://fivethirtyeight.com/features/not-even-scientists-can-easily-explain-p-values/)

<iframe src="https://fivethirtyeight.abcnews.go.com/video/embed/56150342" width="640" height="360" scrolling="no" style="border:none;" allowfullscreen></iframe>

## What does it mean to assume something is true?

<br>

> - When we conduct a hypothesis test, what are the implications of saying "the null hypothesis is assumed to be true"?

  - **Example 1:**
  - What is the least someone could weigh and still be healthy?
  - Assuming the person is 4 foot tall, what is the least they could weight and be healthy?
  - Assuming you are 7 foot tall, what is the least you could weigh and be healthy?
  - **Example 2:**
  - Assuming you are a criminal, should you go to jail?
  - **Example 3:**
  - If someone asks, "Are you stupid or dumb?" what is the assumption?

# Case Study 5 {data-background=#e8c35d}

## The Matthew Effect

<br>

How can hypothesis testing help us understand the Matthew Effect?

## From an idea to a conclusion.

<br>

- "The plural of anecdote is not data."

- What is an [anecdote](https://www.google.com/search?q=anecdote&oq=anecdote&aqs=chrome..69i57j69i60.1926j0j4&sourceid=chrome&ie=UTF-8)?

- How do we tell the difference between a good story and general truth?

- Our case study is built to keep telling Malcom Gladwell's story of the Matthew effect with data (not more anecdotes).











