---
title: ""
---

# Welcome to class! {data-background=#e8c35d}

## End of the Semester

- Come to class on Thursday and complete the Visualization Challenge
- Finish Case Study 7 (tuberculosis)
- Finish Case Study 8 (resume and cover letter)
- Take the Teach One Another quiz
- All work must be turned in by **Wednesday, the 16th**

## Programming Languages

- "R" was written by statisticians, for statisticians. The transition towards data science came later.
  - Used by researchers and scientists
- "Python" is a general-purpose language. Statistical and data science tools came later.
  - Used by programmers and developers
- [Articles in textbook](https://byuistats.github.io/BYUI_CSE150_StatBook/what-is-data-science.html#languages-of-data-science)
- [Google](https://www.google.com/search?q=r+vs+python&rlz=1C1GCEJ_enUS882US882&oq=r+vs+p&aqs=chrome.1.69i57j35i39i457j0i20i263j0l2j69i60l3.3197j0j4&sourceid=chrome&ie=UTF-8) is always a good idea

# Case Study 8 {data-background=#e8c35d}

## Background

For Case Study 8 you need to submit a resume, references you used to build your resume, and a cover letter.  Each being no longer than one page.

## Resumes

Here are the [links to help you with your resume](../resume.html).

_You are writing a 'dream resume' you could use upon graduating from BYU-I. Not a resume on your current skills._ [Here are example resumes of BYU-I data science students.](https://byuidatascience.github.io/resume_example.html#dylan_mcdowell).

**Grading:** I am going to grade you on finding the correct elements to have as well as the layout, look, and feel of your resume. You are trying to get a job with this resume, not just turn in an assignment.

## Resume reference material

As you read through the links and resumes in the previous slide, keep a page of notes.  Good links, good tips, other advice.  This page needs to be submitted as well.


## Cover Letter

This letter is no more than a page.  It should address items related to the following.

> 1. What you learned from the class.
> 2. Things you would change about the class.
> 3. Things you really liked about the class.
> 4. Your favorite topic from Good Reads.
> 5. Your favorite concept from statistics reading.
> 6. What you like about Tableau.



<!----------------
# Dream Resume {data-background=#e8c35d}

- Write a dream resume you would actually use (it doesn't have to be data science!)
  1. Coursework
  2. Work experience
  3. Job requirements

------------->

  
# Your Future {data-background=#e8c35d}

## What are your goals?

- Where do you want to be in a week? A month? A year? 5 years? 10 years?
- How do you get there?


## Hustle culture

[Why are young people pretending to love work?](https://www.nytimes.com/2019/01/26/business/against-hustle-culture-rise-and-grind-tgim.html)

## [Workism Is Making Americans Miserable](https://www.theatlantic.com/ideas/archive/2019/02/religion-workism-making-americans-miserable/583441/?fbclid=IwAR1CiPDQJ8WpE7IyxwXBB_-cyy2gLo3Ecvhjbl3ude9_JRU5XcHTlcVtGKI)

<section style="text-align: left;">

- In the past century, the American conception of work has shifted from jobs to careers to callings-from necessity to status to meaning. In an agrarian or early-manufacturing economy, where tens of millions of people perform similar routinized tasks, there are no delusions about the higher purpose of, say, planting corn or screwing bolts: It's just a job.
- The rise of the professional class and corporate bureaucracies in the early 20th century created the modern journey of a career, a narrative arc bending toward a set of precious initials: VP, SVP, CEO. The upshot is that for today's workists, anything short of finding one's vocational soul mate means a wasted life.
- "We've created this idea that the meaning of life should be found in work," says Oren Cass, the author of the book The Once and Future Worker. "We tell young people that their work should be their passion. 'Don't give up until you find a job that you love!' we say. 'You should be changing the world!' we tell them. That is the message in commencement addresses, in pop culture, and frankly, in media, including The Atlantic."
- **But our desks were never meant to be our altars.**
- The problem with this gospel-Your dream job is out there, so never stop hustling-is that it's a blueprint for spiritual and physical exhaustion. Long hours don't make anybody more productive or creative; they make people stressed, tired and bitter.

</section>


## It's a Wonderful Life

## It's a Wonderful Life

**George:** I couldn't face being cooped up for the rest of my life in a shabby little office...I'd go crazy. I want to do something big and something important.

**Dad:** You know, George, I fell that in a small way we *are* doing something important.

## Personal Revelation

[Advice from the prophet.](https://www.churchofjesuschrist.org/study/general-conference/2018/04/revelation-for-the-church-revelation-for-our-lives?lang=eng)

<!--------------

## Background

For [Case Study 8: Do you want to be a data scientist?](../project.html#Case_Study_8:_Do_you_want_to_be_a_data_scientist) you need to submit a resume, references you used to build your resume, and a cover letter.  Each being no longer than one page.

## Resumes

Here are the [links to help you with your resume](../resume.html).

_You are writing a 'dream resume' as a graduating data science major from BYU-I. Not a resume on your current skills._ [Here are example resumes of BYU-I data science students.](https://byuidatascience.github.io/resume_example.html#dylan_mcdowell).

**Grading:** I am going to grade you on finding the correct elements to have as well as the layout, look, and feel of your resume. You are trying to get a job with this resume, not just turn in an assignment.

## Resume reference material

As you read through the links and resumes in the previous slide, keep a page of notes.  Good links, good tips, other advice.  This page needs to be submitted as well.


## Cover Letter

This letter is no more than a page.  It should address items related to the following.

> 1. What you learned from the class.
> 2. Things you would change about the class.
> 3. Things you really liked about the class.
> 4. Your favorite topic from Good Reads.
> 5. Your favorite concept from statistics reading.
> 6. What you like about Tableau.

--------------------->